### ISSUE TITLE
Why `_log_write` and not `log_write`?

### ISSUE THREAD

**Issue by seppo0010** [twitter/ccommon#15]
In https://github.com/twitter/ccommon/blob/master/include/cc_log.h#L81 and in  https://github.com/twitter/ccommon/blob/master/src/cc_log.c#L168 we declare `_log_write`. The function is not static, and it seems to provide the public interface for logging. Why not call it `log_write` instead?

**Comment by thinkingfish** [comment]
I think this is caught in a gap between a removed feature and a historical artifact.

Previously (k)log_write was a macro that can be turned completely off if the right flag is set, it then calls the function with leading underscore if enabled. See: https://github.com/twitter/twemcache/blob/master/src/mc_klog.h#L91

The handling of CC_LOGGING (set if HAVE_LOGGING is enabled) is slightly misaligned with our modules- it is used in cc_debug.h to turn off debug logging, but the underlying logging module is untouched. But we now use the same logging functionality for both debug logging and command logging, so it seems a better fitting name for this option would be CC_DEBUG_LOGGING, and we may consider re-purposing CC_LOGGING to turn of logging functionality all together.

I'll leave it to @kevyang to answer what he intends to do with this- clean up or put the macro back.
