### ISSUE TITLE
Current ring_array wpos/cap is insufficient

### ISSUE THREAD

**Issue by seppo0010** [twitter/ccommon#53]
Currently, `ring_array` has a `wpos` between `0` and `cap - 1` (it uses modulo). However, this needs to reflect `cap+1` possible states, which are having `0` to `cap` elements.

If cap is 5, the array may have 0, 1, 2, 3, 4 or 5 elements.

See https://github.com/twitter/ccommon/pull/52/files#diff-24026a6092b5fb12913f83a58ff81b31R76 and https://github.com/twitter/ccommon/pull/52/files#diff-24026a6092b5fb12913f83a58ff81b31R98

**Comment by thinkingfish** [comment]
Your premise is that we should use all `cap` slots, but that doesn't have to be- if only `cap -1` slots can be filled, then we can assume `rpos == wpos` only means empty array, and there's no ambiguity.

**Comment by thinkingfish** [comment]
Thanks for the investigation. In that case the modulo operation is not done correctly- `% cap` should mean the buffer size is `cap` for proper offset calculation.
